#!/usr/bin/env bash
# PulseNode — one-command deploy script
set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────────────────
G='\033[0;32m'; C='\033[0;36m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[1m'; N='\033[0m'

echo -e "${C}${B}"
cat << 'BANNER'
  ____        _          _   _           _
 |  _ \ _   _| |___  ___| \ | | ___   __| | ___
 | |_) | | | | / __|/ _ \  \| |/ _ \ / _` |/ _ \
 |  __/| |_| | \__ \  __/ |\  | (_) | (_| |  __/
 |_|    \__,_|_|___/\___|_| \_|\___/ \__,_|\___|
BANNER
echo -e "${N}${G}  VPS monitoring dashboard — deploy script${N}"
echo ""

# ── Prerequisite checks ────────────────────────────────────────────────────────
check() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${R}✗ $1 is not installed.${N}  $2"
    exit 1
  fi
}
check docker   "Install Docker: https://docs.docker.com/get-docker/"
check curl     "Install curl: sudo apt-get install curl"

if ! docker compose version &>/dev/null 2>&1; then
  echo -e "${R}✗ Docker Compose v2 is not available.${N}"
  echo "  Update Docker Desktop or install the Compose plugin:"
  echo "  https://docs.docker.com/compose/install/"
  exit 1
fi

echo -e "${G}✓ Docker         $(docker --version | awk '{print $3}' | tr -d ',')${N}"
echo -e "${G}✓ Docker Compose $(docker compose version --short 2>/dev/null || echo 'v2')${N}"
echo ""

# ── Detect public IP ───────────────────────────────────────────────────────────
DETECTED_IP=$(
  curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null ||
  curl -fsSL --max-time 5 https://ifconfig.me   2>/dev/null ||
  hostname -I 2>/dev/null | awk '{print $1}'    ||
  echo ""
)

echo -e "${C}━━━  Server address  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"
[[ -n "$DETECTED_IP" ]] && echo "  Detected public IP: ${DETECTED_IP}"
printf "  Enter your VPS IP or domain [%s]: " "${DETECTED_IP:-localhost}"
read -r USER_INPUT
HOST="${USER_INPUT:-${DETECTED_IP:-localhost}}"

# Strip protocol prefix if user pasted a full URL
HOST="${HOST#https://}"; HOST="${HOST#http://}"; HOST="${HOST%%/*}"

# Determine protocol
PROTO="http"
printf "  Use HTTPS? (requires a domain with DNS pointing here) [y/N]: "
read -r USE_HTTPS
if [[ "${USE_HTTPS,,}" == "y" ]]; then
  PROTO="https"
fi

BASE_URL="${PROTO}://${HOST}"
# Caddy auto-TLS: use bare domain as site address for HTTPS, else bind to :80
if [[ "${PROTO}" == "https" && ! "${HOST}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  CADDY_SITE_ADDRESS="${HOST}"
else
  CADDY_SITE_ADDRESS=":80"
fi

# ── Optional integrations ──────────────────────────────────────────────────────
echo ""
echo -e "${C}━━━  Optional integrations (press Enter to skip)  ━━━━━━━━━━━━${N}"

printf "  PostgreSQL URL    (postgresql://user:pass@host/db): "
read -r DB_URL

# ── Write .env.local ───────────────────────────────────────────────────────────
gen_secret() {
  openssl rand -hex 32 2>/dev/null || head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 64
}
existing() { [[ -f .env.local ]] && grep "^$1=" .env.local | cut -d= -f2- || true; }
# Keep existing keys on re-run (a new AES_KEY would make stored secrets unreadable);
# new installs get independent values for session signing and encryption.
JWT_SECRET=$(existing JWT_SECRET); JWT_SECRET=${JWT_SECRET:-$(gen_secret)}
AES_KEY=$(existing AES_KEY); AES_KEY=${AES_KEY:-$(gen_secret)}
MASTER_KEY=$(existing MASTER_ENCRYPTION_KEY); MASTER_KEY=${MASTER_KEY:-$AES_KEY}
# One-time token required to create the first admin account in the dashboard.
SETUP_TOKEN=$(gen_secret)

echo ""
echo -e "${C}━━━  Writing .env.local  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"

umask 077
cat > .env.local << EOF
# PulseNode — generated by deploy.sh on $(date -u '+%Y-%m-%d %H:%M UTC')

NEXT_PUBLIC_ORIGIN=${BASE_URL}
NEXT_PUBLIC_GO_API=${BASE_URL}/go
PULSENODE_VPS_IP=${DETECTED_IP}
CADDY_SITE_ADDRESS=${CADDY_SITE_ADDRESS}

WEB_PORT=127.0.0.1:3000
GO_PORT=127.0.0.1:4002

JWT_SECRET=${JWT_SECRET}
AES_KEY=${AES_KEY}
MASTER_ENCRYPTION_KEY=${MASTER_KEY}
PULSENODE_SETUP_TOKEN=${SETUP_TOKEN}

DATABASE_URL=${DB_URL}
EOF
chmod 600 .env.local

echo -e "  ${G}✓ .env.local written (mode 600)${N}"

# ── Build and start ────────────────────────────────────────────────────────────
echo ""
echo -e "${C}━━━  Building and starting containers  ━━━━━━━━━━━━━━━━━━━━━━${N}"
echo -e "  ${Y}This takes a few minutes on first run — grab a coffee ☕${N}"
echo ""

docker compose --env-file .env.local \
  -f docker-compose.yml \
  -f docker-compose.standalone.yml \
  up -d --build

# ── Done ───────────────────────────────────────────────────────────────────────
echo ""
echo -e "${G}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"
echo -e "${G}${B}  ✓  PulseNode is live!${N}"
echo ""
echo -e "  ${B}Dashboard${N}   →  ${C}${BASE_URL}/${N}"
echo -e "  ${Y}First visit: create the admin account with setup token${N} ${B}${SETUP_TOKEN}${N}"
echo -e "  ${Y}(ignore if an admin already exists — the token only works on a fresh install)${N}"
echo -e "  ${B}Containers${N}  →  ${C}${BASE_URL}/containers${N}"
echo -e "  ${B}Stats${N}       →  ${C}${BASE_URL}/stats${N}"
echo -e "  ${B}Processes${N}   →  ${C}${BASE_URL}/processes${N}"
echo -e "  ${B}Databases${N}   →  ${C}${BASE_URL}/databases${N}"
echo -e "  ${B}Networks${N}    →  ${C}${BASE_URL}/networks${N}"
echo ""
echo -e "  To stop:    ${Y}docker compose -f docker-compose.yml -f docker-compose.standalone.yml down${N}"
echo -e "  To update:  ${Y}git pull && ./deploy.sh${N}"
echo -e "${G}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"
