package builder

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// composeHardeningFile is the override file generated next to the user's compose
// file. It is merged AFTER the user's file (and after the Traefik overlay), so it is
// generated by PulseNode, never read from the repo — composepolicy only ever sees
// the user's file.
const composeHardeningFile = "docker-compose.pulsenode-hardening.yml"

var (
	composeServiceNameRe = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)
	composeMemRe         = regexp.MustCompile(`(?i)^[0-9]+(\.[0-9]+)?(b|k|kb|m|mb|g|gb)?$`)
	composeIntRe         = regexp.MustCompile(`^[0-9]+$`)
	composeFloatRe       = regexp.MustCompile(`^[0-9]+(\.[0-9]+)?$`)
)

// composeHardeningOverlay builds the override that gives compose-deployed services
// the same protections single-container deploys get (appHardeningArgs): dropped
// capabilities with a small allow-back list, no-new-privileges, memory/pids/CPU
// ceilings and rotated logs. configJSON is the user's file as printed by
// `docker compose config --format json`; a setting is only added where the service
// did not define it, so an explicit choice (or a limit under deploy.resources) is
// never overridden — compose rejects a mem_limit that disagrees with
// deploy.resources.limits.memory, so both spellings are checked.
//
// The output is JSON (a YAML subset), so service names and values can never inject
// YAML. It returns nil when there is nothing to add.
func composeHardeningOverlay(configJSON []byte) ([]byte, error) {
	var cf struct {
		Services map[string]map[string]json.RawMessage `json:"services"`
	}
	if err := json.Unmarshal(configJSON, &cf); err != nil {
		return nil, fmt.Errorf("unreadable compose config: %w", err)
	}

	mem := envLimit("PULSENODE_APP_MEMORY", "1g")
	pids := envLimit("PULSENODE_APP_PIDS", "1024")
	cpus := envLimit("PULSENODE_APP_CPUS", "")
	if mem != "" && !composeMemRe.MatchString(mem) {
		mem = ""
	}
	if pids != "" && !composeIntRe.MatchString(pids) {
		pids = ""
	}
	if cpus != "" && !composeFloatRe.MatchString(cpus) {
		cpus = ""
	}

	names := make([]string, 0, len(cf.Services))
	for n := range cf.Services {
		names = append(names, n)
	}
	sort.Strings(names)

	out := map[string]map[string]any{}
	for _, name := range names {
		if !composeServiceNameRe.MatchString(name) {
			continue
		}
		svc := cf.Services[name]
		o := map[string]any{}

		// Capabilities: only when the service made no choice of its own.
		if !meaningful(svc["cap_drop"]) {
			o["cap_drop"] = []string{"ALL"}
			o["cap_add"] = appCaps
		}
		if !hasNoNewPrivileges(svc["security_opt"]) {
			o["security_opt"] = []string{"no-new-privileges:true"}
		}

		limits := deployLimits(svc["deploy"])
		if mem != "" && !userSet(svc["mem_limit"]) && !userSet(limits["memory"]) {
			o["mem_limit"] = mem
		}
		if pids != "" && !userSet(svc["pids_limit"]) && !userSet(limits["pids"]) {
			if n, err := strconv.Atoi(pids); err == nil && n > 0 {
				o["pids_limit"] = n
			}
		}
		if cpus != "" && !userSet(svc["cpus"]) && !userSet(limits["cpus"]) {
			if f, err := strconv.ParseFloat(cpus, 64); err == nil && f > 0 {
				o["cpus"] = f
			}
		}
		if !meaningful(svc["logging"]) {
			o["logging"] = map[string]any{
				"driver":  "json-file",
				"options": map[string]string{"max-size": "10m", "max-file": "3"},
			}
		}
		if len(o) > 0 {
			out[name] = o
		}
	}
	if len(out) == 0 {
		return nil, nil
	}
	return json.MarshalIndent(map[string]any{"services": out}, "", "  ")
}

// userSet is meaningful() that also treats the string "0" as unset — compose prints
// unset numeric options as 0 (or "0"), and a literal zero limit means "none".
func userSet(raw json.RawMessage) bool {
	return meaningful(raw) && strings.Trim(strings.TrimSpace(string(raw)), `"`) != "0"
}

func hasNoNewPrivileges(raw json.RawMessage) bool {
	var opts []string
	if json.Unmarshal(raw, &opts) != nil {
		return false
	}
	for _, o := range opts {
		o = strings.ToLower(strings.TrimSpace(o))
		if strings.HasPrefix(o, "no-new-privileges") && !strings.HasSuffix(o, "false") {
			return true
		}
	}
	return false
}

// deployLimits returns deploy.resources.limits as raw values (memory, cpus, pids).
func deployLimits(raw json.RawMessage) map[string]json.RawMessage {
	var d struct {
		Resources struct {
			Limits map[string]json.RawMessage `json:"limits"`
		} `json:"resources"`
	}
	if json.Unmarshal(raw, &d) != nil || d.Resources.Limits == nil {
		return map[string]json.RawMessage{}
	}
	return d.Resources.Limits
}
